/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import11 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ionic-angular/navigation/view-controller';
import * as import19 from 'ionic-angular/components/app/app';
import * as import20 from 'ionic-angular/navigation/nav-controller';
import * as import21 from 'ionic-angular/components/toolbar/toolbar';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/components/tabs/tabs';
import * as import25 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import26 from 'ionic-angular/components/navbar/navbar';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from 'ionic-angular/components/icon/icon';
import * as import29 from 'ionic-angular/components/content/content';
import * as import30 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import31 from 'ionic-angular/navigation/nav-controller-base';
import * as import32 from '@angular/core/src/linker/component_factory_resolver';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from 'ionic-angular/transitions/transition-controller';
import * as import35 from 'ionic-angular/navigation/deep-linker';
import * as import36 from 'ionic-angular/components/nav/nav';
export class Wrapper_ApiDemoPage {
  context:import0.ApiDemoPage;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ApiDemoPage();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ApiDemoApp {
  context:import0.ApiDemoApp;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ApiDemoApp();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ApiDemoPage_Host:import2.RenderComponentType = (null as any);
class _View_ApiDemoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ApiDemoPage_0_4:Wrapper_ApiDemoPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoPage_Host0,renderType_ApiDemoPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ApiDemoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ApiDemoPage_0_4 = new Wrapper_ApiDemoPage();
    this._appEl_0.initComponent(this._ApiDemoPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ApiDemoPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApiDemoPage) && (0 === requestNodeIndex))) { return this._ApiDemoPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ApiDemoPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ApiDemoPage_Host === (null as any))) { (renderType_ApiDemoPage_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ApiDemoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ApiDemoPageNgFactory:import9.ComponentFactory<import0.ApiDemoPage> = new import9.ComponentFactory<import0.ApiDemoPage>('ng-component',viewFactory_ApiDemoPage_Host0,import0.ApiDemoPage);
const styles_ApiDemoPage:any[] = ([] as any[]);
var renderType_ApiDemoPage:import2.RenderComponentType = (null as any);
class _View_ApiDemoPage0 extends import1.AppView<import0.ApiDemoPage> {
  _el_0:any;
  _Header_0_3:import10.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import11.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import12.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import13.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Button_14_4:import14.Wrapper_Button;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Button_17_4:import14.Wrapper_Button;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Button_20_4:import14.Wrapper_Button;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Button_23_4:import14.Wrapper_Button;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Button_26_4:import14.Wrapper_Button;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _Button_32_4:import14.Wrapper_Button;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _Button_35_4:import14.Wrapper_Button;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Button_38_4:import14.Wrapper_Button;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _Button_44_4:import14.Wrapper_Button;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _Button_47_4:import14.Wrapper_Button;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Button_50_4:import14.Wrapper_Button;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import3.AppElement;
  _Button_56_4:import14.Wrapper_Button;
  _text_57:any;
  _el_58:any;
  _Icon_58_3:import15.Wrapper_Icon;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  /*private*/ _appEl_61:import3.AppElement;
  _Button_61_4:import14.Wrapper_Button;
  _text_62:any;
  _el_63:any;
  _Icon_63_3:import15.Wrapper_Icon;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import3.AppElement;
  _Button_66_4:import14.Wrapper_Button;
  _text_67:any;
  _el_68:any;
  _Icon_68_3:import15.Wrapper_Icon;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  /*private*/ _appEl_74:import3.AppElement;
  _Button_74_4:import14.Wrapper_Button;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  /*private*/ _appEl_77:import3.AppElement;
  _Button_77_4:import14.Wrapper_Button;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  /*private*/ _appEl_80:import3.AppElement;
  _Button_80_4:import14.Wrapper_Button;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoPage0,renderType_ApiDemoPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import10.Wrapper_Header(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import18.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import11.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import11.Wrapper_Navbar(this.parentInjector.get(import19.App),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import20.NavController,(null as any)),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import12.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import12.Wrapper_ToolbarTitle(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import21.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Button',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'text-center','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import13.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import13.Wrapper_Content(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import19.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import24.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Colors',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'ion-button','');
    this._appEl_14 = new import3.AppElement(14,9,this,this._el_14);
    var compView_14:any = import14.viewFactory_Button0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Button_14_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_14),this.renderer);
    this._appEl_14.initComponent(this._Button_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'Default',(null as any));
    compView_14.create(this._Button_14_4.context,[([] as any[]).concat([this._text_15])],(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'color','secondary');
    this.renderer.setElementAttribute(this._el_17,'ion-button','');
    this._appEl_17 = new import3.AppElement(17,9,this,this._el_17);
    var compView_17:any = import14.viewFactory_Button0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Button_17_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Button_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'Secondary',(null as any));
    compView_17.create(this._Button_17_4.context,[([] as any[]).concat([this._text_18])],(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'color','danger');
    this.renderer.setElementAttribute(this._el_20,'ion-button','');
    this._appEl_20 = new import3.AppElement(20,9,this,this._el_20);
    var compView_20:any = import14.viewFactory_Button0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Button_20_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_20),this.renderer);
    this._appEl_20.initComponent(this._Button_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'Danger',(null as any));
    compView_20.create(this._Button_20_4.context,[([] as any[]).concat([this._text_21])],(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'color','light');
    this.renderer.setElementAttribute(this._el_23,'ion-button','');
    this._appEl_23 = new import3.AppElement(23,9,this,this._el_23);
    var compView_23:any = import14.viewFactory_Button0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Button_23_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_23),this.renderer);
    this._appEl_23.initComponent(this._Button_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'Light',(null as any));
    compView_23.create(this._Button_23_4.context,[([] as any[]).concat([this._text_24])],(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'color','dark');
    this.renderer.setElementAttribute(this._el_26,'ion-button','');
    this._appEl_26 = new import3.AppElement(26,9,this,this._el_26);
    var compView_26:any = import14.viewFactory_Button0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Button_26_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_26),this.renderer);
    this._appEl_26.initComponent(this._Button_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'Dark',(null as any));
    compView_26.create(this._Button_26_4.context,[([] as any[]).concat([this._text_27])],(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Shapes',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'full','');
    this.renderer.setElementAttribute(this._el_32,'ion-button','');
    this._appEl_32 = new import3.AppElement(32,9,this,this._el_32);
    var compView_32:any = import14.viewFactory_Button0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Button_32_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_32),this.renderer);
    this._appEl_32.initComponent(this._Button_32_4.context,([] as any[]),compView_32);
    this._text_33 = this.renderer.createText((null as any),'Full Button',(null as any));
    compView_32.create(this._Button_32_4.context,[([] as any[]).concat([this._text_33])],(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'block','');
    this.renderer.setElementAttribute(this._el_35,'ion-button','');
    this._appEl_35 = new import3.AppElement(35,9,this,this._el_35);
    var compView_35:any = import14.viewFactory_Button0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Button_35_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._Button_35_4.context,([] as any[]),compView_35);
    this._text_36 = this.renderer.createText((null as any),'Block Button',(null as any));
    compView_35.create(this._Button_35_4.context,[([] as any[]).concat([this._text_36])],(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'ion-button','');
    this.renderer.setElementAttribute(this._el_38,'round','');
    this._appEl_38 = new import3.AppElement(38,9,this,this._el_38);
    var compView_38:any = import14.viewFactory_Button0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Button_38_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Button_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'Round Button',(null as any));
    compView_38.create(this._Button_38_4.context,[([] as any[]).concat([this._text_39])],(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Outlines',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'color','secondary');
    this.renderer.setElementAttribute(this._el_44,'full','');
    this.renderer.setElementAttribute(this._el_44,'ion-button','');
    this.renderer.setElementAttribute(this._el_44,'outline','');
    this._appEl_44 = new import3.AppElement(44,9,this,this._el_44);
    var compView_44:any = import14.viewFactory_Button0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Button_44_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_44),this.renderer);
    this._appEl_44.initComponent(this._Button_44_4.context,([] as any[]),compView_44);
    this._text_45 = this.renderer.createText((null as any),'Outline + Full',(null as any));
    compView_44.create(this._Button_44_4.context,[([] as any[]).concat([this._text_45])],(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'block','');
    this.renderer.setElementAttribute(this._el_47,'color','secondary');
    this.renderer.setElementAttribute(this._el_47,'ion-button','');
    this.renderer.setElementAttribute(this._el_47,'outline','');
    this._appEl_47 = new import3.AppElement(47,9,this,this._el_47);
    var compView_47:any = import14.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_47),this.renderer);
    this._appEl_47.initComponent(this._Button_47_4.context,([] as any[]),compView_47);
    this._text_48 = this.renderer.createText((null as any),'Outline + Block',(null as any));
    compView_47.create(this._Button_47_4.context,[([] as any[]).concat([this._text_48])],(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_50,'color','secondary');
    this.renderer.setElementAttribute(this._el_50,'ion-button','');
    this.renderer.setElementAttribute(this._el_50,'outline','');
    this.renderer.setElementAttribute(this._el_50,'round','');
    this._appEl_50 = new import3.AppElement(50,9,this,this._el_50);
    var compView_50:any = import14.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_50),this.renderer);
    this._appEl_50.initComponent(this._Button_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'Outline + Round',(null as any));
    compView_50.create(this._Button_50_4.context,[([] as any[]).concat([this._text_51])],(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Icons',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_56,'color','dark');
    this.renderer.setElementAttribute(this._el_56,'icon-left','');
    this.renderer.setElementAttribute(this._el_56,'ion-button','');
    this._appEl_56 = new import3.AppElement(56,9,this,this._el_56);
    var compView_56:any = import14.viewFactory_Button0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Button_56_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_56),this.renderer);
    this._appEl_56.initComponent(this._Button_56_4.context,([] as any[]),compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_58,'name','star');
    this.renderer.setElementAttribute(this._el_58,'role','img');
    this._Icon_58_3 = new import15.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_58),this.renderer);
    this._text_59 = this.renderer.createText((null as any),'\n    Left Icon\n  ',(null as any));
      compView_56.create(this._Button_56_4.context,[([] as any[]).concat([
        this._text_57,
        this._el_58,
        this._text_59
      ]
    )],(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_61 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_61,'color','dark');
    this.renderer.setElementAttribute(this._el_61,'icon-right','');
    this.renderer.setElementAttribute(this._el_61,'ion-button','');
    this._appEl_61 = new import3.AppElement(61,9,this,this._el_61);
    var compView_61:any = import14.viewFactory_Button0(this.viewUtils,this.injector(61),this._appEl_61);
    this._Button_61_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_61),this.renderer);
    this._appEl_61.initComponent(this._Button_61_4.context,([] as any[]),compView_61);
    this._text_62 = this.renderer.createText((null as any),'\n    Right Icon\n    ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_63,'name','star');
    this.renderer.setElementAttribute(this._el_63,'role','img');
    this._Icon_63_3 = new import15.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_63),this.renderer);
    this._text_64 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_61.create(this._Button_61_4.context,[([] as any[]).concat([
        this._text_62,
        this._el_63,
        this._text_64
      ]
    )],(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_66 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_66,'color','dark');
    this.renderer.setElementAttribute(this._el_66,'icon-only','');
    this.renderer.setElementAttribute(this._el_66,'ion-button','');
    this._appEl_66 = new import3.AppElement(66,9,this,this._el_66);
    var compView_66:any = import14.viewFactory_Button0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Button_66_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_66),this.renderer);
    this._appEl_66.initComponent(this._Button_66_4.context,([] as any[]),compView_66);
    this._text_67 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_68 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_68,'name','star');
    this.renderer.setElementAttribute(this._el_68,'role','img');
    this._Icon_68_3 = new import15.Wrapper_Icon(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_68),this.renderer);
    this._text_69 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_66.create(this._Button_66_4.context,[([] as any[]).concat([
        this._text_67,
        this._el_68,
        this._text_69
      ]
    )],(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'Sizes',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_74 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_74,'color','light');
    this.renderer.setElementAttribute(this._el_74,'ion-button','');
    this.renderer.setElementAttribute(this._el_74,'large','');
    this._appEl_74 = new import3.AppElement(74,9,this,this._el_74);
    var compView_74:any = import14.viewFactory_Button0(this.viewUtils,this.injector(74),this._appEl_74);
    this._Button_74_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_74),this.renderer);
    this._appEl_74.initComponent(this._Button_74_4.context,([] as any[]),compView_74);
    this._text_75 = this.renderer.createText((null as any),'Large',(null as any));
    compView_74.create(this._Button_74_4.context,[([] as any[]).concat([this._text_75])],(null as any));
    this._text_76 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_77 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_77,'color','light');
    this.renderer.setElementAttribute(this._el_77,'ion-button','');
    this._appEl_77 = new import3.AppElement(77,9,this,this._el_77);
    var compView_77:any = import14.viewFactory_Button0(this.viewUtils,this.injector(77),this._appEl_77);
    this._Button_77_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_77),this.renderer);
    this._appEl_77.initComponent(this._Button_77_4.context,([] as any[]),compView_77);
    this._text_78 = this.renderer.createText((null as any),'Default',(null as any));
    compView_77.create(this._Button_77_4.context,[([] as any[]).concat([this._text_78])],(null as any));
    this._text_79 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_80 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_80,'color','light');
    this.renderer.setElementAttribute(this._el_80,'ion-button','');
    this.renderer.setElementAttribute(this._el_80,'small','');
    this._appEl_80 = new import3.AppElement(80,9,this,this._el_80);
    var compView_80:any = import14.viewFactory_Button0(this.viewUtils,this.injector(80),this._appEl_80);
    this._Button_80_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_80),this.renderer);
    this._appEl_80.initComponent(this._Button_80_4.context,([] as any[]),compView_80);
    this._text_81 = this.renderer.createText((null as any),'Small',(null as any));
    compView_80.create(this._Button_80_4.context,[([] as any[]).concat([this._text_81])],(null as any));
    this._text_82 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_19,
        this._el_20,
        this._text_22,
        this._el_23,
        this._text_25,
        this._el_26,
        this._text_28,
        this._el_29,
        this._text_31,
        this._el_32,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_40,
        this._el_41,
        this._text_43,
        this._el_44,
        this._text_46,
        this._el_47,
        this._text_49,
        this._el_50,
        this._text_52,
        this._el_53,
        this._text_55,
        this._el_56,
        this._text_60,
        this._el_61,
        this._text_65,
        this._el_66,
        this._text_70,
        this._el_71,
        this._text_73,
        this._el_74,
        this._text_76,
        this._el_77,
        this._text_79,
        this._el_80,
        this._text_82
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_83 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._text_83
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import26.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import21.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import27.Button) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Button_14_4.context; }
    if (((token === import27.Button) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_17_4.context; }
    if (((token === import27.Button) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Button_20_4.context; }
    if (((token === import27.Button) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Button_23_4.context; }
    if (((token === import27.Button) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Button_26_4.context; }
    if (((token === import27.Button) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_32_4.context; }
    if (((token === import27.Button) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Button_35_4.context; }
    if (((token === import27.Button) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Button_38_4.context; }
    if (((token === import27.Button) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Button_44_4.context; }
    if (((token === import27.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_47_4.context; }
    if (((token === import27.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Button_50_4.context; }
    if (((token === import28.Icon) && (58 === requestNodeIndex))) { return this._Icon_58_3.context; }
    if (((token === import27.Button) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Button_56_4.context; }
    if (((token === import28.Icon) && (63 === requestNodeIndex))) { return this._Icon_63_3.context; }
    if (((token === import27.Button) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Button_61_4.context; }
    if (((token === import28.Icon) && (68 === requestNodeIndex))) { return this._Icon_68_3.context; }
    if (((token === import27.Button) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Button_66_4.context; }
    if (((token === import27.Button) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Button_74_4.context; }
    if (((token === import27.Button) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Button_77_4.context; }
    if (((token === import27.Button) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Button_80_4.context; }
    if (((token === import29.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Button_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'secondary';
    this._Button_17_4.check_color(currVal_3,throwOnChange,false);
    if (this._Button_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'danger';
    this._Button_20_4.check_color(currVal_4,throwOnChange,false);
    if (this._Button_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    const currVal_5:any = 'light';
    this._Button_23_4.check_color(currVal_5,throwOnChange,false);
    if (this._Button_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_6:any = 'dark';
    this._Button_26_4.check_color(currVal_6,throwOnChange,false);
    if (this._Button_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    const currVal_7:any = '';
    this._Button_32_4.check_full(currVal_7,throwOnChange,false);
    if (this._Button_32_4.detectChangesInternal(this,this._el_32,throwOnChange)) { this._appEl_32.componentView.markAsCheckOnce(); }
    const currVal_8:any = '';
    this._Button_35_4.check_block(currVal_8,throwOnChange,false);
    if (this._Button_35_4.detectChangesInternal(this,this._el_35,throwOnChange)) { this._appEl_35.componentView.markAsCheckOnce(); }
    const currVal_9:any = '';
    this._Button_38_4.check_round(currVal_9,throwOnChange,false);
    if (this._Button_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    const currVal_10:any = '';
    this._Button_44_4.check_outline(currVal_10,throwOnChange,false);
    const currVal_11:any = '';
    this._Button_44_4.check_full(currVal_11,throwOnChange,false);
    const currVal_12:any = 'secondary';
    this._Button_44_4.check_color(currVal_12,throwOnChange,false);
    if (this._Button_44_4.detectChangesInternal(this,this._el_44,throwOnChange)) { this._appEl_44.componentView.markAsCheckOnce(); }
    const currVal_13:any = '';
    this._Button_47_4.check_outline(currVal_13,throwOnChange,false);
    const currVal_14:any = '';
    this._Button_47_4.check_block(currVal_14,throwOnChange,false);
    const currVal_15:any = 'secondary';
    this._Button_47_4.check_color(currVal_15,throwOnChange,false);
    if (this._Button_47_4.detectChangesInternal(this,this._el_47,throwOnChange)) { this._appEl_47.componentView.markAsCheckOnce(); }
    const currVal_16:any = '';
    this._Button_50_4.check_outline(currVal_16,throwOnChange,false);
    const currVal_17:any = '';
    this._Button_50_4.check_round(currVal_17,throwOnChange,false);
    const currVal_18:any = 'secondary';
    this._Button_50_4.check_color(currVal_18,throwOnChange,false);
    if (this._Button_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    const currVal_19:any = 'dark';
    this._Button_56_4.check_color(currVal_19,throwOnChange,false);
    if (this._Button_56_4.detectChangesInternal(this,this._el_56,throwOnChange)) { this._appEl_56.componentView.markAsCheckOnce(); }
    const currVal_20:any = 'star';
    this._Icon_58_3.check_name(currVal_20,throwOnChange,false);
    this._Icon_58_3.detectChangesInternal(this,this._el_58,throwOnChange);
    const currVal_22:any = 'dark';
    this._Button_61_4.check_color(currVal_22,throwOnChange,false);
    if (this._Button_61_4.detectChangesInternal(this,this._el_61,throwOnChange)) { this._appEl_61.componentView.markAsCheckOnce(); }
    const currVal_23:any = 'star';
    this._Icon_63_3.check_name(currVal_23,throwOnChange,false);
    this._Icon_63_3.detectChangesInternal(this,this._el_63,throwOnChange);
    const currVal_25:any = 'dark';
    this._Button_66_4.check_color(currVal_25,throwOnChange,false);
    if (this._Button_66_4.detectChangesInternal(this,this._el_66,throwOnChange)) { this._appEl_66.componentView.markAsCheckOnce(); }
    const currVal_26:any = 'star';
    this._Icon_68_3.check_name(currVal_26,throwOnChange,false);
    this._Icon_68_3.detectChangesInternal(this,this._el_68,throwOnChange);
    const currVal_28:any = '';
    this._Button_74_4.check_large(currVal_28,throwOnChange,false);
    const currVal_29:any = 'light';
    this._Button_74_4.check_color(currVal_29,throwOnChange,false);
    if (this._Button_74_4.detectChangesInternal(this,this._el_74,throwOnChange)) { this._appEl_74.componentView.markAsCheckOnce(); }
    const currVal_30:any = 'light';
    this._Button_77_4.check_color(currVal_30,throwOnChange,false);
    if (this._Button_77_4.detectChangesInternal(this,this._el_77,throwOnChange)) { this._appEl_77.componentView.markAsCheckOnce(); }
    const currVal_31:any = '';
    this._Button_80_4.check_small(currVal_31,throwOnChange,false);
    const currVal_32:any = 'light';
    this._Button_80_4.check_color(currVal_32,throwOnChange,false);
    if (this._Button_80_4.detectChangesInternal(this,this._el_80,throwOnChange)) { this._appEl_80.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_14_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_17_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_20_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_26_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_32_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_35_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_38_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_44_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_47_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_56_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_61_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_66_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_74_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_77_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_80_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_21:any = this._Icon_58_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_58,'hide',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_24:any = this._Icon_63_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_63,'hide',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._Icon_68_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_68,'hide',currVal_27);
      this._expr_27 = currVal_27;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_58_3.context.ngOnDestroy();
    this._Icon_63_3.context.ngOnDestroy();
    this._Icon_68_3.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_ApiDemoPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ApiDemoPage> {
  if ((renderType_ApiDemoPage === (null as any))) { (renderType_ApiDemoPage = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_ApiDemoPage,{})); }
  return new _View_ApiDemoPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_ApiDemoApp_Host:import2.RenderComponentType = (null as any);
class _View_ApiDemoApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ApiDemoApp_0_4:Wrapper_ApiDemoApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoApp_Host0,renderType_ApiDemoApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ApiDemoApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ApiDemoApp_0_4 = new Wrapper_ApiDemoApp();
    this._appEl_0.initComponent(this._ApiDemoApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ApiDemoApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApiDemoApp) && (0 === requestNodeIndex))) { return this._ApiDemoApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ApiDemoApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ApiDemoApp_Host === (null as any))) { (renderType_ApiDemoApp_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ApiDemoApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const ApiDemoAppNgFactory:import9.ComponentFactory<import0.ApiDemoApp> = new import9.ComponentFactory<import0.ApiDemoApp>('ng-component',viewFactory_ApiDemoApp_Host0,import0.ApiDemoApp);
const styles_ApiDemoApp:any[] = ([] as any[]);
var renderType_ApiDemoApp:import2.RenderComponentType = (null as any);
class _View_ApiDemoApp0 extends import1.AppView<import0.ApiDemoApp> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Nav_0_4:import30.Wrapper_Nav;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoApp0,renderType_ApiDemoApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import30.Wrapper_Nav(this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import31.NavControllerBase,(null as any)),this.parentInjector.get(import19.App),this.parentInjector.get(import16.Config),this.parentInjector.get(import22.Keyboard),new import17.ElementRef(this._el_0),this.parentInjector.get(import23.NgZone),this.renderer,this.parentInjector.get(import32.ComponentFactoryResolver),this.parentInjector.get(import33.GestureController),this.parentInjector.get(import34.TransitionController),this.parentInjector.get(import35.DeepLinker,(null as any)));
    this._appEl_0.initComponent(this._Nav_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Nav_0_4.context,([] as any[]),(null as any));
    this.init(([] as any[]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.root;
    this._Nav_0_4.check_root(currVal_0,throwOnChange,false);
    this._Nav_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.context.ngAfterViewInit(); } }
  }
}
export function viewFactory_ApiDemoApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ApiDemoApp> {
  if ((renderType_ApiDemoApp === (null as any))) { (renderType_ApiDemoApp = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_ApiDemoApp,{})); }
  return new _View_ApiDemoApp0(viewUtils,parentInjector,declarationEl);
}