import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import11 from '@angular/core/src/linker/component_factory';
export declare const Page1NgFactory: import11.ComponentFactory<import3.Page1>;
export declare function viewFactory_Page10(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.Page1>;
export declare const Page2NgFactory: import11.ComponentFactory<import3.Page2>;
export declare function viewFactory_Page20(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.Page2>;
export declare const ApiDemoAppNgFactory: import11.ComponentFactory<import3.ApiDemoApp>;
export declare function viewFactory_ApiDemoApp0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.ApiDemoApp>;
