import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/component_factory';
export declare const LoginNgFactory: import10.ComponentFactory<import3.Login>;
export declare function viewFactory_Login0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.Login>;
export declare const LogoutNgFactory: import10.ComponentFactory<import3.Logout>;
export declare function viewFactory_Logout0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.Logout>;
export declare const ApiDemoAppNgFactory: import10.ComponentFactory<import3.ApiDemoApp>;
export declare function viewFactory_ApiDemoApp0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.ApiDemoApp>;
