/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from './menu';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/linker/query_list';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import18 from '../backdrop/backdrop.ngfactory';
export declare class Wrapper_Menu {
    _eventHandler: Function;
    context: import0.Menu;
    _changed: boolean;
    _expr_0: any;
    _expr_1: any;
    _expr_2: any;
    _expr_3: any;
    _expr_4: any;
    _expr_5: any;
    _expr_6: any;
    _expr_7: any;
    subscription0: any;
    subscription1: any;
    subscription2: any;
    constructor(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any);
    ngOnDetach(view: import2.AppView<any>, componentView: import2.AppView<any>, el: any): void;
    ngOnDestroy(): void;
    check_content(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_id(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_side(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_type(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_enabled(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_swipeEnabled(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_persistent(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    check_maxEdgeStart(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    ngDoCheck(view: import2.AppView<any>, el: any, throwOnChange: boolean): boolean;
    checkHost(view: import2.AppView<any>, componentView: import2.AppView<any>, el: any, throwOnChange: boolean): void;
    handleEvent(eventName: string, $event: any): boolean;
    subscribe(view: import2.AppView<any>, _eventHandler: any, emit0: boolean, emit1: boolean, emit2: boolean): void;
}
export declare const MenuNgFactory: import8.ComponentFactory<import0.Menu>;
export declare class View_Menu0 extends import2.AppView<import0.Menu> {
    _viewQuery_Backdrop_0: import6.QueryList<any>;
    _el_0: any;
    _el_1: any;
    _Backdrop_1_3: import18.Wrapper_Backdrop;
    constructor(viewUtils: import3.ViewUtils, parentView: import2.AppView<any>, parentIndex: number, parentElement: any);
    createInternal(rootSelector: string): import8.ComponentRef<any>;
    injectorGetInternal(token: any, requestNodeIndex: number, notFoundResult: any): any;
    detectChangesInternal(throwOnChange: boolean): void;
}
