/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '../module';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '../util/dom-controller';
import * as import11 from '../components/menu/menu-controller';
import * as import12 from '../components/app/app';
import * as import13 from '../gestures/gesture-controller';
import * as import14 from '@angular/core/src/application_init';
import * as import15 from '@angular/core/src/testability/testability';
import * as import16 from '@angular/core/src/application_ref';
import * as import17 from '@angular/core/src/linker/compiler';
import * as import18 from '../gestures/gesture-config';
import * as import19 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import20 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import21 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import22 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import23 from '@angular/core/src/linker/view_utils';
import * as import24 from '@angular/platform-browser/src/browser/title';
import * as import25 from '@angular/http/src/backends/browser_xhr';
import * as import26 from '@angular/http/src/base_response_options';
import * as import27 from '@angular/http/src/backends/xhr_backend';
import * as import28 from '@angular/http/src/base_request_options';
import * as import29 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import30 from '@angular/forms/src/form_builder';
import * as import31 from '../components/action-sheet/action-sheet';
import * as import32 from '../components/alert/alert';
import * as import33 from '../util/events';
import * as import34 from '../util/form';
import * as import35 from '../util/haptic';
import * as import36 from '../util/keyboard';
import * as import37 from '../components/loading/loading';
import * as import38 from '@angular/common/src/location/location';
import * as import39 from '../components/modal/modal';
import * as import40 from '../components/picker/picker';
import * as import41 from '../components/popover/popover';
import * as import42 from '../components/tap-click/tap-click';
import * as import43 from '../components/toast/toast';
import * as import44 from '../transitions/transition-controller';
import * as import45 from '@angular/core/src/di/injector';
import * as import46 from '../components/action-sheet/action-sheet-component.ngfactory';
import * as import47 from '../components/alert/alert-component.ngfactory';
import * as import48 from '../components/app/app-root.ngfactory';
import * as import49 from '../components/loading/loading-component.ngfactory';
import * as import50 from '../components/modal/modal-component.ngfactory';
import * as import51 from '../components/picker/picker-component.ngfactory';
import * as import52 from '../components/popover/popover-component.ngfactory';
import * as import53 from '../components/toast/toast-component.ngfactory';
import * as import54 from '@angular/core/src/application_tokens';
import * as import55 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import56 from '@angular/platform-browser/src/dom/events/key_events';
import * as import57 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import58 from '@angular/core/src/zone/ng_zone';
import * as import59 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import60 from '@angular/common/src/location/platform_location';
import * as import61 from '@angular/common/src/location/location_strategy';
import * as import62 from '../navigation/url-serializer';
import * as import63 from '../navigation/deep-linker';
import * as import64 from '../platform/query-params';
import * as import65 from '../platform/platform-registry';
import * as import66 from '../platform/platform';
import * as import67 from '../config/config';
import * as import68 from '../config/mode-registry';
import * as import69 from '../transitions/transition-registry';
import * as import70 from '@angular/core/src/console';
import * as import71 from '@angular/core/src/i18n/tokens';
import * as import72 from '@angular/core/src/error_handler';
import * as import73 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import74 from '@angular/platform-browser/src/dom/animation_driver';
import * as import75 from '@angular/core/src/render/api';
import * as import76 from '@angular/core/src/security';
import * as import77 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import78 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import79 from '@angular/http/src/interfaces';
import * as import80 from '@angular/http/src/http';
import * as import81 from '../components/app/app-root';
import * as import82 from '@angular/core/src/linker/view';
import * as import83 from '@angular/core/src/render/api';
import * as import84 from '@angular/core/src/linker/view_utils';
import * as import85 from '@angular/core/src/metadata/view';
import * as import86 from '@angular/core/src/linker/view_type';
import * as import87 from '@angular/core/src/change_detection/change_detection';
import * as import88 from '@angular/core/src/linker/component_factory';
import * as import89 from '../components/nav/nav';
import * as import90 from '../components/nav/nav.ngfactory';
import * as import91 from '../navigation/view-controller';
import * as import92 from '../navigation/nav-controller';
import * as import93 from '@angular/core/src/linker/element_ref';
import * as import94 from '@angular/core/src/linker/component_factory_resolver';
import * as import95 from '../components/toolbar/toolbar.ngfactory';
import * as import96 from '../components/navbar/navbar';
import * as import97 from '../components/navbar/navbar.ngfactory';
import * as import98 from '../components/toolbar/toolbar-title';
import * as import99 from '../components/toolbar/toolbar-title.ngfactory';
import * as import100 from '../components/toolbar/toolbar-item.ngfactory';
import * as import101 from '@angular/core/src/linker/query_list';
import * as import102 from '../components/button/button';
import * as import103 from '../components/button/button.ngfactory';
import * as import104 from '../components/content/content';
import * as import105 from '../components/content/content.ngfactory';
import * as import106 from '../components/list/list.ngfactory';
import * as import107 from '../components/item/item';
import * as import108 from '../components/item/item.ngfactory';
import * as import109 from '../components/list/list-header.ngfactory';
import * as import110 from '../components/item/item-reorder.ngfactory';
import * as import111 from '@angular/core/src/linker/view_container';
import * as import112 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import113 from '../components/toolbar/toolbar';
import * as import114 from '../components/tabs/tabs';
import * as import115 from '../components/item/item-reorder';
import * as import116 from '@angular/core/src/linker/template_ref';
import * as import117 from '../components/toolbar/toolbar-item';
import * as import118 from '../components/list/list-header';
import * as import119 from '@angular/common/src/directives/ng_for';
import * as import120 from '../components/list/list';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _IonicModule_7:import8.IonicModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ConfigToken_12:any;
  _UrlToken_13:any;
  _QueryParams_14:any;
  _PlatformConfigToken_15:any;
  _UserAgentToken_16:any;
  _NavigatorPlatformToken_17:any;
  _DocumentDirToken_18:any;
  _DocLangToken_19:any;
  _Platform_20:any;
  _Config_21:any;
  _DomController_22:import10.DomController;
  _MenuController_23:import11.MenuController;
  _App_24:import12.App;
  _GestureController_25:import13.GestureController;
  _APP_INITIALIZER_26:any[];
  _ApplicationInitStatus_27:import14.ApplicationInitStatus;
  _Testability_28:import15.Testability;
  _ApplicationRef__29:import16.ApplicationRef_;
  __ApplicationRef_30:any;
  __Compiler_31:import17.Compiler;
  __APP_ID_32:any;
  __DOCUMENT_33:any;
  __HAMMER_GESTURE_CONFIG_34:import18.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_35:any[];
  __EventManager_36:import19.EventManager;
  __DomSharedStylesHost_37:import20.DomSharedStylesHost;
  __AnimationDriver_38:any;
  __DomRootRenderer_39:import21.DomRootRenderer_;
  __RootRenderer_40:any;
  __DomSanitizer_41:import22.DomSanitizerImpl;
  __Sanitizer_42:any;
  __ViewUtils_43:import23.ViewUtils;
  __IterableDiffers_44:any;
  __KeyValueDiffers_45:any;
  __SharedStylesHost_46:any;
  __Title_47:import24.Title;
  __BrowserXhr_48:import25.BrowserXhr;
  __ResponseOptions_49:import26.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import27.XHRBackend;
  __RequestOptions_52:import28.BaseRequestOptions;
  __Http_53:any;
  __RadioControlRegistry_54:import29.RadioControlRegistry;
  __FormBuilder_55:import30.FormBuilder;
  __AppRootToken_56:any;
  __DeepLinkConfigToken_57:any;
  __ActionSheetController_58:import31.ActionSheetController;
  __AlertController_59:import32.AlertController;
  __Events_60:import33.Events;
  __Form_61:import34.Form;
  __Haptic_62:import35.Haptic;
  __Keyboard_63:import36.Keyboard;
  __LoadingController_64:import37.LoadingController;
  __LocationStrategy_65:any;
  __Location_66:import38.Location;
  __ModalController_67:import39.ModalController;
  __PickerController_68:import40.PickerController;
  __PopoverController_69:import41.PopoverController;
  __TapClick_70:import42.TapClick;
  __ToastController_71:import43.ToastController;
  __TransitionController_72:import44.TransitionController;
  __UrlSerializer_73:any;
  __DeepLinker_74:any;
  constructor(parent:import45.Injector) {
    super(parent,[
      import46.ActionSheetCmpNgFactory,
      import47.AlertCmpNgFactory,
      import48.IonicAppNgFactory,
      import49.LoadingCmpNgFactory,
      import50.ModalCmpNgFactory,
      import51.PickerCmpNgFactory,
      import52.PopoverCmpNgFactory,
      import53.ToastCmpNgFactory,
      ApiDemoAppNgFactory,
      ApiDemoPageNgFactory,
      import48.IonicAppNgFactory
    ]
    ,[import48.IonicAppNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_30():any {
    if ((this.__ApplicationRef_30 == null)) { (this.__ApplicationRef_30 = this._ApplicationRef__29); }
    return this.__ApplicationRef_30;
  }
  get _Compiler_31():import17.Compiler {
    if ((this.__Compiler_31 == null)) { (this.__Compiler_31 = new import17.Compiler()); }
    return this.__Compiler_31;
  }
  get _APP_ID_32():any {
    if ((this.__APP_ID_32 == null)) { (this.__APP_ID_32 = import54._appIdRandomProviderFactory()); }
    return this.__APP_ID_32;
  }
  get _DOCUMENT_33():any {
    if ((this.__DOCUMENT_33 == null)) { (this.__DOCUMENT_33 = import4._document()); }
    return this.__DOCUMENT_33;
  }
  get _HAMMER_GESTURE_CONFIG_34():import18.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_34 == null)) { (this.__HAMMER_GESTURE_CONFIG_34 = new import18.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_34;
  }
  get _EVENT_MANAGER_PLUGINS_35():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_35 == null)) { (this.__EVENT_MANAGER_PLUGINS_35 = [
      new import55.DomEventsPlugin(),
      new import56.KeyEventsPlugin(),
      new import57.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_34)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_35;
  }
  get _EventManager_36():import19.EventManager {
    if ((this.__EventManager_36 == null)) { (this.__EventManager_36 = new import19.EventManager(this._EVENT_MANAGER_PLUGINS_35,this.parent.get(import58.NgZone))); }
    return this.__EventManager_36;
  }
  get _DomSharedStylesHost_37():import20.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_37 == null)) { (this.__DomSharedStylesHost_37 = new import20.DomSharedStylesHost(this._DOCUMENT_33)); }
    return this.__DomSharedStylesHost_37;
  }
  get _AnimationDriver_38():any {
    if ((this.__AnimationDriver_38 == null)) { (this.__AnimationDriver_38 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_38;
  }
  get _DomRootRenderer_39():import21.DomRootRenderer_ {
    if ((this.__DomRootRenderer_39 == null)) { (this.__DomRootRenderer_39 = new import21.DomRootRenderer_(this._DOCUMENT_33,this._EventManager_36,this._DomSharedStylesHost_37,this._AnimationDriver_38,this._APP_ID_32)); }
    return this.__DomRootRenderer_39;
  }
  get _RootRenderer_40():any {
    if ((this.__RootRenderer_40 == null)) { (this.__RootRenderer_40 = import59._createConditionalRootRenderer(this._DomRootRenderer_39,this.parent.get(import59.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_40;
  }
  get _DomSanitizer_41():import22.DomSanitizerImpl {
    if ((this.__DomSanitizer_41 == null)) { (this.__DomSanitizer_41 = new import22.DomSanitizerImpl()); }
    return this.__DomSanitizer_41;
  }
  get _Sanitizer_42():any {
    if ((this.__Sanitizer_42 == null)) { (this.__Sanitizer_42 = this._DomSanitizer_41); }
    return this.__Sanitizer_42;
  }
  get _ViewUtils_43():import23.ViewUtils {
    if ((this.__ViewUtils_43 == null)) { (this.__ViewUtils_43 = new import23.ViewUtils(this._RootRenderer_40,this._Sanitizer_42)); }
    return this.__ViewUtils_43;
  }
  get _IterableDiffers_44():any {
    if ((this.__IterableDiffers_44 == null)) { (this.__IterableDiffers_44 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_44;
  }
  get _KeyValueDiffers_45():any {
    if ((this.__KeyValueDiffers_45 == null)) { (this.__KeyValueDiffers_45 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_45;
  }
  get _SharedStylesHost_46():any {
    if ((this.__SharedStylesHost_46 == null)) { (this.__SharedStylesHost_46 = this._DomSharedStylesHost_37); }
    return this.__SharedStylesHost_46;
  }
  get _Title_47():import24.Title {
    if ((this.__Title_47 == null)) { (this.__Title_47 = new import24.Title()); }
    return this.__Title_47;
  }
  get _BrowserXhr_48():import25.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import25.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import26.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import26.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import27.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import27.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import28.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import28.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import5.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _RadioControlRegistry_54():import29.RadioControlRegistry {
    if ((this.__RadioControlRegistry_54 == null)) { (this.__RadioControlRegistry_54 = new import29.RadioControlRegistry()); }
    return this.__RadioControlRegistry_54;
  }
  get _FormBuilder_55():import30.FormBuilder {
    if ((this.__FormBuilder_55 == null)) { (this.__FormBuilder_55 = new import30.FormBuilder()); }
    return this.__FormBuilder_55;
  }
  get _AppRootToken_56():any {
    if ((this.__AppRootToken_56 == null)) { (this.__AppRootToken_56 = import1.ApiDemoApp); }
    return this.__AppRootToken_56;
  }
  get _DeepLinkConfigToken_57():any {
    if ((this.__DeepLinkConfigToken_57 == null)) { (this.__DeepLinkConfigToken_57 = (null as any)); }
    return this.__DeepLinkConfigToken_57;
  }
  get _ActionSheetController_58():import31.ActionSheetController {
    if ((this.__ActionSheetController_58 == null)) { (this.__ActionSheetController_58 = new import31.ActionSheetController(this._App_24)); }
    return this.__ActionSheetController_58;
  }
  get _AlertController_59():import32.AlertController {
    if ((this.__AlertController_59 == null)) { (this.__AlertController_59 = new import32.AlertController(this._App_24)); }
    return this.__AlertController_59;
  }
  get _Events_60():import33.Events {
    if ((this.__Events_60 == null)) { (this.__Events_60 = new import33.Events()); }
    return this.__Events_60;
  }
  get _Form_61():import34.Form {
    if ((this.__Form_61 == null)) { (this.__Form_61 = new import34.Form()); }
    return this.__Form_61;
  }
  get _Haptic_62():import35.Haptic {
    if ((this.__Haptic_62 == null)) { (this.__Haptic_62 = new import35.Haptic(this._Platform_20)); }
    return this.__Haptic_62;
  }
  get _Keyboard_63():import36.Keyboard {
    if ((this.__Keyboard_63 == null)) { (this.__Keyboard_63 = new import36.Keyboard(this._Config_21,this.parent.get(import58.NgZone),this._DomController_22)); }
    return this.__Keyboard_63;
  }
  get _LoadingController_64():import37.LoadingController {
    if ((this.__LoadingController_64 == null)) { (this.__LoadingController_64 = new import37.LoadingController(this._App_24)); }
    return this.__LoadingController_64;
  }
  get _LocationStrategy_65():any {
    if ((this.__LocationStrategy_65 == null)) { (this.__LocationStrategy_65 = import8.provideLocationStrategy(this.parent.get(import60.PlatformLocation),this.parent.get(import61.APP_BASE_HREF,(null as any)),this._Config_21)); }
    return this.__LocationStrategy_65;
  }
  get _Location_66():import38.Location {
    if ((this.__Location_66 == null)) { (this.__Location_66 = new import38.Location(this._LocationStrategy_65)); }
    return this.__Location_66;
  }
  get _ModalController_67():import39.ModalController {
    if ((this.__ModalController_67 == null)) { (this.__ModalController_67 = new import39.ModalController(this._App_24)); }
    return this.__ModalController_67;
  }
  get _PickerController_68():import40.PickerController {
    if ((this.__PickerController_68 == null)) { (this.__PickerController_68 = new import40.PickerController(this._App_24)); }
    return this.__PickerController_68;
  }
  get _PopoverController_69():import41.PopoverController {
    if ((this.__PopoverController_69 == null)) { (this.__PopoverController_69 = new import41.PopoverController(this._App_24)); }
    return this.__PopoverController_69;
  }
  get _TapClick_70():import42.TapClick {
    if ((this.__TapClick_70 == null)) { (this.__TapClick_70 = new import42.TapClick(this._Config_21,this._App_24,this.parent.get(import58.NgZone),this._GestureController_25)); }
    return this.__TapClick_70;
  }
  get _ToastController_71():import43.ToastController {
    if ((this.__ToastController_71 == null)) { (this.__ToastController_71 = new import43.ToastController(this._App_24)); }
    return this.__ToastController_71;
  }
  get _TransitionController_72():import44.TransitionController {
    if ((this.__TransitionController_72 == null)) { (this.__TransitionController_72 = new import44.TransitionController(this._Config_21)); }
    return this.__TransitionController_72;
  }
  get _UrlSerializer_73():any {
    if ((this.__UrlSerializer_73 == null)) { (this.__UrlSerializer_73 = import62.setupUrlSerializer(this._DeepLinkConfigToken_57)); }
    return this.__UrlSerializer_73;
  }
  get _DeepLinker_74():any {
    if ((this.__DeepLinker_74 == null)) { (this.__DeepLinker_74 = import63.setupDeepLinker(this._App_24,this._UrlSerializer_73,this._Location_66)); }
    return this.__DeepLinker_74;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._IonicModule_7 = new import8.IonicModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ConfigToken_12 = (null as any);
    this._UrlToken_13 = import8.provideLocationHref();
    this._QueryParams_14 = import64.setupQueryParams(this._UrlToken_13);
    this._PlatformConfigToken_15 = import65.providePlatformConfigs();
    this._UserAgentToken_16 = import8.provideUserAgent();
    this._NavigatorPlatformToken_17 = import8.provideNavigatorPlatform();
    this._DocumentDirToken_18 = import8.provideDocumentDirection();
    this._DocLangToken_19 = import8.provideDocumentLang();
    this._Platform_20 = import66.setupPlatform(this._PlatformConfigToken_15,this._QueryParams_14,this._UserAgentToken_16,this._NavigatorPlatformToken_17,this._DocumentDirToken_18,this._DocLangToken_19,this.parent.get(import58.NgZone));
    this._Config_21 = import67.setupConfig(this._ConfigToken_12,this._QueryParams_14,this._Platform_20);
    this._DomController_22 = new import10.DomController();
    this._MenuController_23 = new import11.MenuController();
    this._App_24 = new import12.App(this._Config_21,this._Platform_20,this._MenuController_23);
    this._GestureController_25 = new import13.GestureController(this._App_24);
    this._APP_INITIALIZER_26 = [
      import68.registerModeConfigs(this._Config_21),
      import69.registerTransitions(this._Config_21),
      import33.setupProvideEvents(this._Platform_20,this._DomController_22),
      import42.setupTapClick(this._Config_21,this._App_24,this.parent.get(import58.NgZone),this._GestureController_25)
    ]
    ;
    this._ApplicationInitStatus_27 = new import14.ApplicationInitStatus(this._APP_INITIALIZER_26);
    this._Testability_28 = new import15.Testability(this.parent.get(import58.NgZone));
    this._ApplicationRef__29 = new import16.ApplicationRef_(this.parent.get(import58.NgZone),this.parent.get(import70.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_27,this.parent.get(import15.TestabilityRegistry,(null as any)),this._Testability_28);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.IonicModule)) { return this._IonicModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import71.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import72.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import67.ConfigToken)) { return this._ConfigToken_12; }
    if ((token === import64.UrlToken)) { return this._UrlToken_13; }
    if ((token === import64.QueryParams)) { return this._QueryParams_14; }
    if ((token === import65.PlatformConfigToken)) { return this._PlatformConfigToken_15; }
    if ((token === import66.UserAgentToken)) { return this._UserAgentToken_16; }
    if ((token === import66.NavigatorPlatformToken)) { return this._NavigatorPlatformToken_17; }
    if ((token === import66.DocumentDirToken)) { return this._DocumentDirToken_18; }
    if ((token === import66.DocLangToken)) { return this._DocLangToken_19; }
    if ((token === import66.Platform)) { return this._Platform_20; }
    if ((token === import67.Config)) { return this._Config_21; }
    if ((token === import10.DomController)) { return this._DomController_22; }
    if ((token === import11.MenuController)) { return this._MenuController_23; }
    if ((token === import12.App)) { return this._App_24; }
    if ((token === import13.GestureController)) { return this._GestureController_25; }
    if ((token === import14.APP_INITIALIZER)) { return this._APP_INITIALIZER_26; }
    if ((token === import14.ApplicationInitStatus)) { return this._ApplicationInitStatus_27; }
    if ((token === import15.Testability)) { return this._Testability_28; }
    if ((token === import16.ApplicationRef_)) { return this._ApplicationRef__29; }
    if ((token === import16.ApplicationRef)) { return this._ApplicationRef_30; }
    if ((token === import17.Compiler)) { return this._Compiler_31; }
    if ((token === import54.APP_ID)) { return this._APP_ID_32; }
    if ((token === import73.DOCUMENT)) { return this._DOCUMENT_33; }
    if ((token === import57.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_34; }
    if ((token === import19.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_35; }
    if ((token === import19.EventManager)) { return this._EventManager_36; }
    if ((token === import20.DomSharedStylesHost)) { return this._DomSharedStylesHost_37; }
    if ((token === import74.AnimationDriver)) { return this._AnimationDriver_38; }
    if ((token === import21.DomRootRenderer)) { return this._DomRootRenderer_39; }
    if ((token === import75.RootRenderer)) { return this._RootRenderer_40; }
    if ((token === import22.DomSanitizer)) { return this._DomSanitizer_41; }
    if ((token === import76.Sanitizer)) { return this._Sanitizer_42; }
    if ((token === import23.ViewUtils)) { return this._ViewUtils_43; }
    if ((token === import77.IterableDiffers)) { return this._IterableDiffers_44; }
    if ((token === import78.KeyValueDiffers)) { return this._KeyValueDiffers_45; }
    if ((token === import20.SharedStylesHost)) { return this._SharedStylesHost_46; }
    if ((token === import24.Title)) { return this._Title_47; }
    if ((token === import25.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import26.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import79.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import27.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import28.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import80.Http)) { return this._Http_53; }
    if ((token === import29.RadioControlRegistry)) { return this._RadioControlRegistry_54; }
    if ((token === import30.FormBuilder)) { return this._FormBuilder_55; }
    if ((token === import81.AppRootToken)) { return this._AppRootToken_56; }
    if ((token === import62.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_57; }
    if ((token === import31.ActionSheetController)) { return this._ActionSheetController_58; }
    if ((token === import32.AlertController)) { return this._AlertController_59; }
    if ((token === import33.Events)) { return this._Events_60; }
    if ((token === import34.Form)) { return this._Form_61; }
    if ((token === import35.Haptic)) { return this._Haptic_62; }
    if ((token === import36.Keyboard)) { return this._Keyboard_63; }
    if ((token === import37.LoadingController)) { return this._LoadingController_64; }
    if ((token === import61.LocationStrategy)) { return this._LocationStrategy_65; }
    if ((token === import38.Location)) { return this._Location_66; }
    if ((token === import39.ModalController)) { return this._ModalController_67; }
    if ((token === import40.PickerController)) { return this._PickerController_68; }
    if ((token === import41.PopoverController)) { return this._PopoverController_69; }
    if ((token === import42.TapClick)) { return this._TapClick_70; }
    if ((token === import43.ToastController)) { return this._ToastController_71; }
    if ((token === import44.TransitionController)) { return this._TransitionController_72; }
    if ((token === import62.UrlSerializer)) { return this._UrlSerializer_73; }
    if ((token === import63.DeepLinker)) { return this._DeepLinker_74; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__29.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
export class Wrapper_ApiDemoApp {
  /*private*/ _eventHandler:Function;
  context:import1.ApiDemoApp;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import1.ApiDemoApp();
  }
  ngOnDetach(view:import82.AppView<any>,componentView:import82.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import82.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import82.AppView<any>,componentView:import82.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import82.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
export class Wrapper_ApiDemoPage {
  /*private*/ _eventHandler:Function;
  context:import1.ApiDemoPage;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import1.ApiDemoPage(p0);
  }
  ngOnDetach(view:import82.AppView<any>,componentView:import82.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import82.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import82.AppView<any>,componentView:import82.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import82.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ApiDemoApp_Host:import83.RenderComponentType = import84.createRenderComponentType('',0,import85.ViewEncapsulation.None,([] as any[]),{});
class View_ApiDemoApp_Host0 extends import82.AppView<any> {
  _el_0:any;
  compView_0:import82.AppView<import1.ApiDemoApp>;
  _ApiDemoApp_0_3:Wrapper_ApiDemoApp;
  constructor(viewUtils:import84.ViewUtils,parentView:import82.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiDemoApp_Host0,renderType_ApiDemoApp_Host,import86.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import87.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import88.ComponentRef<any> {
    this._el_0 = import84.selectOrCreateRenderHostElement(this.renderer,'ng-component',import84.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ApiDemoApp0(this.viewUtils,this,0,this._el_0);
    this._ApiDemoApp_0_3 = new Wrapper_ApiDemoApp();
    this.compView_0.create(this._ApiDemoApp_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import88.ComponentRef_<any>(0,this,this._el_0,this._ApiDemoApp_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ApiDemoApp) && (0 === requestNodeIndex))) { return this._ApiDemoApp_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoApp_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ApiDemoAppNgFactory:import88.ComponentFactory<import1.ApiDemoApp> = new import88.ComponentFactory<import1.ApiDemoApp>('ng-component',View_ApiDemoApp_Host0,import1.ApiDemoApp);
const styles_ApiDemoApp:any[] = ([] as any[]);
var renderType_ApiDemoApp:import83.RenderComponentType = import84.createRenderComponentType('',0,import85.ViewEncapsulation.None,styles_ApiDemoApp,{});
export class View_ApiDemoApp0 extends import82.AppView<import1.ApiDemoApp> {
  _el_0:any;
  compView_0:import82.AppView<import89.Nav>;
  _Nav_0_3:import90.Wrapper_Nav;
  constructor(viewUtils:import84.ViewUtils,parentView:import82.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiDemoApp0,renderType_ApiDemoApp,import86.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import87.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import88.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import84.createRenderElement(this.renderer,parentRenderNode,'ion-nav',import84.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import90.View_Nav0(this.viewUtils,this,0,this._el_0);
    this._Nav_0_3 = new import90.Wrapper_Nav(this.parentView.injectorGet(import91.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import92.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import12.App,this.parentIndex),this.parentView.injectorGet(import67.Config,this.parentIndex),this.parentView.injectorGet(import36.Keyboard,this.parentIndex),new import93.ElementRef(this._el_0),this.parentView.injectorGet(import58.NgZone,this.parentIndex),this.renderer,this.parentView.injectorGet(import94.ComponentFactoryResolver,this.parentIndex),this.parentView.injectorGet(import13.GestureController,this.parentIndex),this.parentView.injectorGet(import44.TransitionController,this.parentIndex),this.parentView.injectorGet(import63.DeepLinker,this.parentIndex,(null as any)),this.parentView.injectorGet(import10.DomController,this.parentIndex));
    this.compView_0.create(this._Nav_0_3.context);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import89.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.root;
    this._Nav_0_3.check_root(currVal_0_0_0,throwOnChange,false);
    this._Nav_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}
var renderType_ApiDemoPage_Host:import83.RenderComponentType = import84.createRenderComponentType('',0,import85.ViewEncapsulation.None,([] as any[]),{});
class View_ApiDemoPage_Host0 extends import82.AppView<any> {
  _el_0:any;
  compView_0:import82.AppView<import1.ApiDemoPage>;
  _ApiDemoPage_0_3:Wrapper_ApiDemoPage;
  constructor(viewUtils:import84.ViewUtils,parentView:import82.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiDemoPage_Host0,renderType_ApiDemoPage_Host,import86.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import87.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import88.ComponentRef<any> {
    this._el_0 = import84.selectOrCreateRenderHostElement(this.renderer,'ng-component',import84.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ApiDemoPage0(this.viewUtils,this,0,this._el_0);
    this._ApiDemoPage_0_3 = new Wrapper_ApiDemoPage(this.injectorGet(import92.NavController,this.parentIndex));
    this.compView_0.create(this._ApiDemoPage_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import88.ComponentRef_<any>(0,this,this._el_0,this._ApiDemoPage_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ApiDemoPage) && (0 === requestNodeIndex))) { return this._ApiDemoPage_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoPage_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ApiDemoPageNgFactory:import88.ComponentFactory<import1.ApiDemoPage> = new import88.ComponentFactory<import1.ApiDemoPage>('ng-component',View_ApiDemoPage_Host0,import1.ApiDemoPage);
const styles_ApiDemoPage:any[] = ([] as any[]);
var renderType_ApiDemoPage:import83.RenderComponentType = import84.createRenderComponentType('',0,import85.ViewEncapsulation.None,styles_ApiDemoPage,{});
export class View_ApiDemoPage0 extends import82.AppView<import1.ApiDemoPage> {
  _el_0:any;
  _Header_0_3:import95.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  compView_2:import82.AppView<import96.Navbar>;
  _Navbar_2_3:import97.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  compView_4:import82.AppView<import98.ToolbarTitle>;
  _ToolbarTitle_4_3:import99.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import100.Wrapper_ToolbarItem;
  _query_Button_7_0:import101.QueryList<any>;
  _text_8:any;
  _el_9:any;
  compView_9:import82.AppView<import102.Button>;
  _Button_9_3:import103.Wrapper_Button;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import82.AppView<import104.Content>;
  _Content_15_3:import105.Wrapper_Content;
  _text_16:any;
  _el_17:any;
  _List_17_3:import106.Wrapper_List;
  _text_18:any;
  _el_19:any;
  compView_19:import82.AppView<import107.Item>;
  _Item_19_3:import108.Wrapper_Item;
  _ListHeader_19_4:import109.Wrapper_ListHeader;
  _query_Label_19_0:import101.QueryList<any>;
  _query_Button_19_1:import101.QueryList<any>;
  _query_Icon_19_2:import101.QueryList<any>;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _ItemGroup_22_3:import108.Wrapper_ItemGroup;
  _ItemReorder_22_4:import110.Wrapper_ItemReorder;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import111.ViewContainer;
  _TemplateRef_24_5:any;
  _NgFor_24_6:import112.Wrapper_NgFor;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import84.ViewUtils,parentView:import82.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApiDemoPage0,renderType_ApiDemoPage,import86.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import87.ChangeDetectorStatus.CheckAlways);
    this._expr_52 = import87.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import88.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import84.createRenderElement(this.renderer,parentRenderNode,'ion-header',import84.EMPTY_INLINE_ARRAY,(null as any));
    this._Header_0_3 = new import95.Wrapper_Header(this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_0),this.renderer,this.parentView.injectorGet(import91.ViewController,this.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = import84.createRenderElement(this.renderer,this._el_0,'ion-navbar',new import84.InlineArray2(2,'class','toolbar'),(null as any));
    this.compView_2 = new import97.View_Navbar0(this.viewUtils,this,2,this._el_2);
    this._Navbar_2_3 = new import97.Wrapper_Navbar(this.parentView.injectorGet(import12.App,this.parentIndex),this.parentView.injectorGet(import91.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import92.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import84.createRenderElement(this.renderer,(null as any),'ion-title',import84.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import99.View_ToolbarTitle0(this.viewUtils,this,4,this._el_4);
    this._ToolbarTitle_4_3 = new import99.Wrapper_ToolbarTitle(this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_4),this.renderer,this.parentView.injectorGet(import113.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._text_5 = this.renderer.createText((null as any),'Item Reorder',(null as any));
    this.compView_4.create(this._ToolbarTitle_4_3.context);
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = import84.createRenderElement(this.renderer,(null as any),'ion-buttons',new import84.InlineArray2(2,'end',''),(null as any));
    this._ToolbarItem_7_3 = new import100.Wrapper_ToolbarItem(this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_7),this.renderer,this.parentView.injectorGet(import113.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._query_Button_7_0 = new import101.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = import84.createRenderElement(this.renderer,this._el_7,'button',new import84.InlineArray2(2,'ion-button',''),(null as any));
    this.compView_9 = new import103.View_Button0(this.viewUtils,this,9,this._el_9);
    this._Button_9_3 = new import103.Wrapper_Button('',this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    this.compView_9.create(this._Button_9_3.context);
    this._text_11 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._Navbar_2_3.context);
    this._text_13 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_15 = import84.createRenderElement(this.renderer,parentRenderNode,'ion-content',new import84.InlineArray2(2,'fullscreen',''),(null as any));
    this.compView_15 = new import105.View_Content0(this.viewUtils,this,15,this._el_15);
    this._Content_15_3 = new import105.Wrapper_Content(this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_15),this.renderer,this.parentView.injectorGet(import12.App,this.parentIndex),this.parentView.injectorGet(import36.Keyboard,this.parentIndex),this.parentView.injectorGet(import58.NgZone,this.parentIndex),this.parentView.injectorGet(import91.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import114.Tabs,this.parentIndex,(null as any)),this.parentView.injectorGet(import10.DomController,this.parentIndex));
    this._text_16 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_17 = import84.createRenderElement(this.renderer,(null as any),'ion-list',new import84.InlineArray2(2,'class','chat-sliding-demo'),(null as any));
    this._List_17_3 = new import106.Wrapper_List(this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_17),this.renderer,this.parentView.injectorGet(import13.GestureController,this.parentIndex),this.parentView.injectorGet(import10.DomController,this.parentIndex));
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._el_19 = import84.createRenderElement(this.renderer,this._el_17,'ion-list-header',new import84.InlineArray2(2,'class','item'),(null as any));
    this.compView_19 = new import108.View_Item0(this.viewUtils,this,19,this._el_19);
    this._Item_19_3 = new import108.Wrapper_Item(this.parentView.injectorGet(import34.Form,this.parentIndex),this.parentView.injectorGet(import67.Config,this.parentIndex),new import93.ElementRef(this._el_19),this.renderer,this.parentView.injectorGet(import115.ItemReorder,this.parentIndex,(null as any)));
    this._ListHeader_19_4 = new import109.Wrapper_ListHeader(this.parentView.injectorGet(import67.Config,this.parentIndex),this.renderer,new import93.ElementRef(this._el_19),(null as any));
    this._query_Label_19_0 = new import101.QueryList<any>();
    this._query_Button_19_1 = new import101.QueryList<any>();
    this._query_Icon_19_2 = new import101.QueryList<any>();
    this._text_20 = this.renderer.createText((null as any),'\n      Playlist\n    ',(null as any));
    this._query_Label_19_0.reset(([] as any[]));
    this._Item_19_3.context.contentLabel = this._query_Label_19_0.first;
    this.compView_19.create(this._Item_19_3.context);
    this._text_21 = this.renderer.createText(this._el_17,'\n\n    ',(null as any));
    this._el_22 = import84.createRenderElement(this.renderer,this._el_17,'ion-item-group',import84.EMPTY_INLINE_ARRAY,(null as any));
    this._ItemGroup_22_3 = new import108.Wrapper_ItemGroup();
    this._ItemReorder_22_4 = new import110.Wrapper_ItemReorder(new import93.ElementRef(this._el_22),this.renderer,this.parentView.injectorGet(import58.NgZone,this.parentIndex),this._Content_15_3.context);
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._vc_24 = new import111.ViewContainer(24,22,this,this._anchor_24);
    this._TemplateRef_24_5 = new import116.TemplateRef_(this,24,this._anchor_24);
    this._NgFor_24_6 = new import112.Wrapper_NgFor(this._vc_24.vcRef,this._TemplateRef_24_5,this.parentView.injectorGet(import77.IterableDiffers,this.parentIndex),this.ref);
    this._text_25 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n  ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n',(null as any));
    this.compView_15.create(this._Content_15_3.context);
    this._text_28 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import84.subscribeToRenderElement(this,this._el_9,new import84.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_1:Function = import84.subscribeToRenderElement(this,this._el_22,new import84.InlineArray2(2,'ionItemReorder',(null as any)),this.eventHandler(this.handleEvent_22));
    this._ItemReorder_22_4.subscribe(this,this.eventHandler(this.handleEvent_22),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import98.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_3.context; }
    if (((token === import102.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_9_3.context; }
    if (((token === import117.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_7_3.context; }
    if (((token === import96.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_2_3.context; }
    if (((token === import113.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Header_0_3.context; }
    if (((token === import107.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_19_3.context; }
    if (((token === import118.ListHeader) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ListHeader_19_4.context; }
    if (((token === import116.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import119.NgFor) && (24 === requestNodeIndex))) { return this._NgFor_24_6.context; }
    if (((token === import107.ItemGroup) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ItemGroup_22_3.context; }
    if (((token === import115.ItemReorder) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ItemReorder_22_4.context; }
    if (((token === import120.List) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._List_17_3.context; }
    if (((token === import104.Content) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Content_15_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._Navbar_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_3.ngDoCheck(this,this._el_4,throwOnChange)) { this.compView_4.markAsCheckOnce(); }
    this._ToolbarItem_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    if (this._Button_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    const currVal_15_0_0:any = '';
    this._Content_15_3.check_fullscreen(currVal_15_0_0,throwOnChange,false);
    if (this._Content_15_3.ngDoCheck(this,this._el_15,throwOnChange)) { this.compView_15.markAsCheckOnce(); }
    this._List_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    if (this._Item_19_3.ngDoCheck(this,this._el_19,throwOnChange)) { this.compView_19.markAsCheckOnce(); }
    this._ListHeader_19_4.ngDoCheck(this,this._el_19,throwOnChange);
    this._ItemGroup_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = this.context.editing;
    this._ItemReorder_22_4.check_reorder(currVal_22_1_0,throwOnChange,false);
    this._ItemReorder_22_4.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_24_0_0:any = this.context.songs;
    this._NgFor_24_6.check_ngForOf(currVal_24_0_0,throwOnChange,false);
    this._NgFor_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([this._Button_9_3.context]);
        this._ToolbarItem_7_3.context._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset(([] as any[]));
        this._Item_19_3.context._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset(([] as any[]));
        this._Item_19_3.context._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_19_3.context.ngAfterContentInit(); }
    }
    this._Navbar_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    const currVal_52:any = import84.inlineInterpolate(1,'',this.context.editButton,'');
    if (import84.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_10,currVal_52);
      this._expr_52 = currVal_52;
    }
    this._Content_15_3.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._ItemReorder_22_4.checkHost(this,this,this._el_22,throwOnChange);
    this.compView_2.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
    this.compView_9.detectChanges(throwOnChange);
    this.compView_15.detectChanges(throwOnChange);
    this.compView_19.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_24.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_4.destroy();
    this.compView_9.destroy();
    this.compView_15.destroy();
    this.compView_19.destroy();
    this._ItemReorder_22_4.ngOnDestroy();
    this._Content_15_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 2))) { cb(this._el_7,ctx); }
    if (((nodeIndex == 2) && (ngContentIndex == 3))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._text_12,ctx);
    }
    if (((nodeIndex == 4) && (ngContentIndex == 0))) { cb(this._text_5,ctx); }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) { cb(this._text_10,ctx); }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 1))) {
      cb(this._text_16,ctx);
      cb(this._el_17,ctx);
      cb(this._text_27,ctx);
    }
    if (((nodeIndex == 15) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 2))) { cb(this._text_20,ctx); }
    if (((nodeIndex == 19) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 19) && (ngContentIndex == 4))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import82.AppView<any> {
    if ((nodeIndex == 24)) { return new View_ApiDemoPage1(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.toggleEdit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'ionItemReorder')) {
      const pd_sub_0:any = ((<any>this.context.reorderData($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ApiDemoPage1 extends import82.AppView<any> {
  _el_0:any;
  compView_0:import82.AppView<import107.Item>;
  _Item_0_3:import108.Wrapper_Item;
  _ItemContent_0_4:import108.Wrapper_ItemContent;
  _query_Label_0_0:import101.QueryList<any>;
  _query_Button_0_1:import101.QueryList<any>;
  _query_Icon_0_2:import101.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import84.ViewUtils,parentView:import82.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import111.ViewContainer) {
    super(View_ApiDemoPage1,renderType_ApiDemoPage,import86.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import87.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_14 = import87.UNINITIALIZED;
    this._expr_15 = import87.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import88.ComponentRef<any> {
    this._el_0 = import84.createRenderElement(this.renderer,(null as any),'ion-item',new import84.InlineArray2(2,'class','item item-block'),(null as any));
    this.compView_0 = new import108.View_Item0(this.viewUtils,this,0,this._el_0);
    this._Item_0_3 = new import108.Wrapper_Item(this.parentView.parentView.injectorGet(import34.Form,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import67.Config,this.parentView.parentIndex),new import93.ElementRef(this._el_0),this.renderer,(<View_ApiDemoPage0>this.parentView)._ItemReorder_22_4.context);
    this._ItemContent_0_4 = new import108.Wrapper_ItemContent();
    this._query_Label_0_0 = new import101.QueryList<any>();
    this._query_Button_0_1 = new import101.QueryList<any>();
    this._query_Icon_0_2 = new import101.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = import84.createRenderElement(this.renderer,(null as any),'h2',import84.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_5 = import84.createRenderElement(this.renderer,(null as any),'p',import84.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_3.context.contentLabel = this._query_Label_0_0.first;
    this.compView_0.create(this._Item_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import107.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_3.context; }
    if (((token === import107.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._ItemContent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_3.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_3.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_3.context.ngAfterContentInit(); }
    }
    const currVal_14:any = import84.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import84.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_3,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import84.inlineInterpolate(2,'',this.context.$implicit.band,' • ',this.context.$implicit.album,'');
    if (import84.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_6,currVal_15);
      this._expr_15 = currVal_15;
    }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 2))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_4,ctx);
      cb(this._el_5,ctx);
      cb(this._text_7,ctx);
    }
    if (((nodeIndex == 0) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 4))) {  }
  }
}