/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import11 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/navigation/nav-controller';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from 'ionic-angular/platform/platform';
import * as import33 from '@angular/forms/src/directives/ng_control';
import * as import34 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import35 from 'ionic-angular/components/navbar/navbar';
import * as import36 from 'ionic-angular/components/avatar/avatar';
import * as import37 from 'ionic-angular/components/label/label';
import * as import38 from 'ionic-angular/components/item/item';
import * as import39 from 'ionic-angular/components/input/input';
import * as import40 from 'ionic-angular/components/icon/icon';
import * as import41 from 'ionic-angular/components/list/list';
import * as import42 from 'ionic-angular/components/content/content';
import * as import43 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import44 from 'ionic-angular/navigation/nav-controller-base';
import * as import45 from '@angular/core/src/linker/component_factory_resolver';
import * as import46 from 'ionic-angular/transitions/transition-controller';
import * as import47 from 'ionic-angular/navigation/deep-linker';
import * as import48 from 'ionic-angular/components/nav/nav';
export class Wrapper_ApiDemoPage {
  context:import0.ApiDemoPage;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ApiDemoPage();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
export class Wrapper_ApiDemoApp {
  context:import0.ApiDemoApp;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ApiDemoApp();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ApiDemoPage_Host:import2.RenderComponentType = (null as any);
class _View_ApiDemoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ApiDemoPage_0_4:Wrapper_ApiDemoPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoPage_Host0,renderType_ApiDemoPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ApiDemoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ApiDemoPage_0_4 = new Wrapper_ApiDemoPage();
    this._appEl_0.initComponent(this._ApiDemoPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ApiDemoPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApiDemoPage) && (0 === requestNodeIndex))) { return this._ApiDemoPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ApiDemoPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ApiDemoPage_Host === (null as any))) { (renderType_ApiDemoPage_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ApiDemoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ApiDemoPageNgFactory:import9.ComponentFactory<import0.ApiDemoPage> = new import9.ComponentFactory<import0.ApiDemoPage>('ng-component',viewFactory_ApiDemoPage_Host0,import0.ApiDemoPage);
const styles_ApiDemoPage:any[] = ['.label-demo[_ngcontent-%COMP%]   .mobile1[_ngcontent-%COMP%], .label-demo[_ngcontent-%COMP%]   .mobile2[_ngcontent-%COMP%] {\n    position: absolute;\n    right: 5px;\n    bottom: 5px;\n  }\n\n  .label-demo[_ngcontent-%COMP%]   .mobile1[_ngcontent-%COMP%] {\n    right: 35px;\n  }'];
var renderType_ApiDemoPage:import2.RenderComponentType = (null as any);
class _View_ApiDemoPage0 extends import1.AppView<import0.ApiDemoPage> {
  _el_0:any;
  _Header_0_3:import10.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import11.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import12.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import13.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import14.Wrapper_List;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Item_13_4:import15.Wrapper_Item;
  _ItemContent_13_5:import15.Wrapper_ItemContent;
  _query_Label_13_0:import16.QueryList<any>;
  _query_Button_13_1:import16.QueryList<any>;
  _query_Icon_13_2:import16.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Avatar_15_3:import17.Wrapper_Avatar;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _Label_20_3:import18.Wrapper_Label;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Item_25_4:import15.Wrapper_Item;
  _ItemContent_25_5:import15.Wrapper_ItemContent;
  _query_Label_25_0:import16.QueryList<any>;
  _query_Button_25_1:import16.QueryList<any>;
  _query_Icon_25_2:import16.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import18.Wrapper_Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TextInput_30_4:import19.Wrapper_TextInput;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import20.Wrapper_Icon;
  _text_33:any;
  _el_34:any;
  _Icon_34_3:import20.Wrapper_Icon;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Item_37_4:import15.Wrapper_Item;
  _ItemContent_37_5:import15.Wrapper_ItemContent;
  _query_Label_37_0:import16.QueryList<any>;
  _query_Button_37_1:import16.QueryList<any>;
  _query_Icon_37_2:import16.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _Label_39_3:import18.Wrapper_Label;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _TextInput_42_4:import19.Wrapper_TextInput;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _Item_45_4:import15.Wrapper_Item;
  _ItemContent_45_5:import15.Wrapper_ItemContent;
  _query_Label_45_0:import16.QueryList<any>;
  _query_Button_45_1:import16.QueryList<any>;
  _query_Icon_45_2:import16.QueryList<any>;
  _text_46:any;
  _el_47:any;
  _Label_47_3:import18.Wrapper_Label;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _TextInput_50_4:import19.Wrapper_TextInput;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import3.AppElement;
  _Item_53_4:import15.Wrapper_Item;
  _ItemContent_53_5:import15.Wrapper_ItemContent;
  _query_Label_53_0:import16.QueryList<any>;
  _query_Button_53_1:import16.QueryList<any>;
  _query_Icon_53_2:import16.QueryList<any>;
  _text_54:any;
  _el_55:any;
  _Label_55_3:import18.Wrapper_Label;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  /*private*/ _appEl_58:import3.AppElement;
  _TextArea_58_4:import19.Wrapper_TextArea;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _Item_62_4:import15.Wrapper_Item;
  _ItemContent_62_5:import15.Wrapper_ItemContent;
  _query_Label_62_0:import16.QueryList<any>;
  _query_Button_62_1:import16.QueryList<any>;
  _query_Icon_62_2:import16.QueryList<any>;
  _text_63:any;
  _el_64:any;
  _Label_64_3:import18.Wrapper_Label;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import3.AppElement;
  _TextArea_67_4:import19.Wrapper_TextArea;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  /*private*/ _appEl_70:import3.AppElement;
  _Item_70_4:import15.Wrapper_Item;
  _ItemContent_70_5:import15.Wrapper_ItemContent;
  _query_Label_70_0:import16.QueryList<any>;
  _query_Button_70_1:import16.QueryList<any>;
  _query_Icon_70_2:import16.QueryList<any>;
  _text_71:any;
  _el_72:any;
  _Label_72_3:import18.Wrapper_Label;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  /*private*/ _appEl_76:import3.AppElement;
  _Item_76_4:import15.Wrapper_Item;
  _ItemContent_76_5:import15.Wrapper_ItemContent;
  _query_Label_76_0:import16.QueryList<any>;
  _query_Button_76_1:import16.QueryList<any>;
  _query_Icon_76_2:import16.QueryList<any>;
  _text_77:any;
  _el_78:any;
  _Label_78_3:import18.Wrapper_Label;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  /*private*/ _appEl_82:import3.AppElement;
  _Item_82_4:import15.Wrapper_Item;
  _ItemContent_82_5:import15.Wrapper_ItemContent;
  _query_Label_82_0:import16.QueryList<any>;
  _query_Button_82_1:import16.QueryList<any>;
  _query_Icon_82_2:import16.QueryList<any>;
  _text_83:any;
  _el_84:any;
  _Label_84_3:import18.Wrapper_Label;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoPage0,renderType_ApiDemoPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import10.Wrapper_Header(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import11.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import11.Wrapper_Navbar(this.parentInjector.get(import24.App),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import12.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import12.Wrapper_ToolbarTitle(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Label',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','label-demo');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import13.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import13.Wrapper_Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import24.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_11_3 = new import14.Wrapper_List(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','item item-block');
    this.renderer.setElementAttribute(this._el_13,'no-lines','');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import15.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Item_13_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_13),this.renderer);
    this._ItemContent_13_5 = new import15.Wrapper_ItemContent();
    this._query_Label_13_0 = new import16.QueryList<any>();
    this._query_Button_13_1 = new import16.QueryList<any>();
    this._query_Icon_13_2 = new import16.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_15,'item-left','');
    this._Avatar_15_3 = new import17.Wrapper_Avatar();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'img',(null as any));
    this.renderer.setElementAttribute(this._el_17,'src','ionic.svg');
    this._text_18 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_20_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_20),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Ionic',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_13_0.reset([this._Label_20_3.context]);
    this._Item_13_4.context.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_4.context,[
      ([] as any[]).concat([this._el_15]),
      ([] as any[]).concat([this._el_20]),
      ([] as any[]).concat([
        this._text_14,
        this._text_19,
        this._text_22
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import3.AppElement(25,11,this,this._el_25);
    var compView_25:any = import15.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import15.Wrapper_ItemContent();
    this._query_Label_25_0 = new import16.QueryList<any>();
    this._query_Button_25_1 = new import16.QueryList<any>();
    this._query_Icon_25_2 = new import16.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_27,'color','primary');
    this.renderer.setElementAttribute(this._el_27,'stacked','');
    this._Label_27_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_27),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Mobile',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'type','tel');
    this.renderer.setElementAttribute(this._el_30,'value','+1 (555) 123-1234');
    this._appEl_30 = new import3.AppElement(30,25,this,this._el_30);
    var compView_30:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(30),this._appEl_30);
    this._TextInput_30_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import31.Form),this._Item_25_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import32.Platform),new import22.ElementRef(this._el_30),this.renderer,this._Content_9_4.context,this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import33.NgControl,(null as any)));
    this._appEl_30.initComponent(this._TextInput_30_4.context,([] as any[]),compView_30);
    compView_30.create(this._TextInput_30_4.context,([] as any[]),(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','mobile1');
    this.renderer.setElementAttribute(this._el_32,'color','primary');
    this.renderer.setElementAttribute(this._el_32,'ios','ios-chatbubbles-outline');
    this.renderer.setElementAttribute(this._el_32,'item-right','');
    this.renderer.setElementAttribute(this._el_32,'md','md-chatbubbles');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import20.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','mobile2');
    this.renderer.setElementAttribute(this._el_34,'color','primary');
    this.renderer.setElementAttribute(this._el_34,'ios','ios-call-outline');
    this.renderer.setElementAttribute(this._el_34,'item-right','');
    this.renderer.setElementAttribute(this._el_34,'md','md-call');
    this.renderer.setElementAttribute(this._el_34,'role','img');
    this._Icon_34_3 = new import20.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3.context]);
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_27]),
      ([] as any[]).concat([
        this._text_26,
        this._text_29,
        this._text_31,
        this._text_33,
        this._text_35
      ]
      ),
      ([] as any[]).concat([this._el_30]),
      ([] as any[]).concat([
        this._el_32,
        this._el_34
      ]
      )
    ]
    ,(null as any));
    this._text_36 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this._appEl_37 = new import3.AppElement(37,11,this,this._el_37);
    var compView_37:any = import15.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_37),this.renderer);
    this._ItemContent_37_5 = new import15.Wrapper_ItemContent();
    this._query_Label_37_0 = new import16.QueryList<any>();
    this._query_Button_37_1 = new import16.QueryList<any>();
    this._query_Icon_37_2 = new import16.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_39,'color','primary');
    this.renderer.setElementAttribute(this._el_39,'stacked','');
    this._Label_39_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_39),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Email',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'type','email');
    this.renderer.setElementAttribute(this._el_42,'value','hi@ionic.io');
    this._appEl_42 = new import3.AppElement(42,37,this,this._el_42);
    var compView_42:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(42),this._appEl_42);
    this._TextInput_42_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import31.Form),this._Item_37_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import32.Platform),new import22.ElementRef(this._el_42),this.renderer,this._Content_9_4.context,this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import33.NgControl,(null as any)));
    this._appEl_42.initComponent(this._TextInput_42_4.context,([] as any[]),compView_42);
    compView_42.create(this._TextInput_42_4.context,([] as any[]),(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_37_0.reset([this._Label_39_3.context]);
    this._Item_37_4.context.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_39]),
      ([] as any[]).concat([
        this._text_38,
        this._text_41,
        this._text_43
      ]
      ),
      ([] as any[]).concat([this._el_42]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_44 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','item item-block');
    this._appEl_45 = new import3.AppElement(45,11,this,this._el_45);
    var compView_45:any = import15.viewFactory_Item0(this.viewUtils,this.injector(45),this._appEl_45);
    this._Item_45_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_45),this.renderer);
    this._ItemContent_45_5 = new import15.Wrapper_ItemContent();
    this._query_Label_45_0 = new import16.QueryList<any>();
    this._query_Button_45_1 = new import16.QueryList<any>();
    this._query_Icon_45_2 = new import16.QueryList<any>();
    this._appEl_45.initComponent(this._Item_45_4.context,([] as any[]),compView_45);
    this._text_46 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_47,'color','primary');
    this.renderer.setElementAttribute(this._el_47,'stacked','');
    this._Label_47_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_47),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Birthday',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_50,'type','text');
    this.renderer.setElementAttribute(this._el_50,'value','November 21, 2013');
    this._appEl_50 = new import3.AppElement(50,45,this,this._el_50);
    var compView_50:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(50),this._appEl_50);
    this._TextInput_50_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import31.Form),this._Item_45_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import32.Platform),new import22.ElementRef(this._el_50),this.renderer,this._Content_9_4.context,this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import33.NgControl,(null as any)));
    this._appEl_50.initComponent(this._TextInput_50_4.context,([] as any[]),compView_50);
    compView_50.create(this._TextInput_50_4.context,([] as any[]),(null as any));
    this._text_51 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_45_0.reset([this._Label_47_3.context]);
    this._Item_45_4.context.contentLabel = this._query_Label_45_0.first;
    compView_45.create(this._Item_45_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_47]),
      ([] as any[]).concat([
        this._text_46,
        this._text_49,
        this._text_51
      ]
      ),
      ([] as any[]).concat([this._el_50]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_52 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','item item-block');
    this._appEl_53 = new import3.AppElement(53,11,this,this._el_53);
    var compView_53:any = import15.viewFactory_Item0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Item_53_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_53),this.renderer);
    this._ItemContent_53_5 = new import15.Wrapper_ItemContent();
    this._query_Label_53_0 = new import16.QueryList<any>();
    this._query_Button_53_1 = new import16.QueryList<any>();
    this._query_Icon_53_2 = new import16.QueryList<any>();
    this._appEl_53.initComponent(this._Item_53_4.context,([] as any[]),compView_53);
    this._text_54 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_55,'color','primary');
    this.renderer.setElementAttribute(this._el_55,'stacked','');
    this._Label_55_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_55),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Address',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_58,'value','121 S Pinckney St\nMadison WI 53703\nUnited States');
    this._appEl_58 = new import3.AppElement(58,53,this,this._el_58);
    var compView_58:any = import19.viewFactory_TextArea0(this.viewUtils,this.injector(58),this._appEl_58);
    this._TextArea_58_4 = new import19.Wrapper_TextArea(this.parentInjector.get(import21.Config),this.parentInjector.get(import31.Form),this._Item_53_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import32.Platform),new import22.ElementRef(this._el_58),this.renderer,this._Content_9_4.context,this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import33.NgControl,(null as any)));
    this._appEl_58.initComponent(this._TextArea_58_4.context,([] as any[]),compView_58);
    this._text_59 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_58.create(this._TextArea_58_4.context,([] as any[]),(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_53_0.reset([this._Label_55_3.context]);
    this._Item_53_4.context.contentLabel = this._query_Label_53_0.first;
    compView_53.create(this._Item_53_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_55]),
      ([] as any[]).concat([
        this._text_54,
        this._text_57,
        this._text_60
      ]
      ),
      ([] as any[]).concat([this._el_58]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','item item-block');
    this._appEl_62 = new import3.AppElement(62,11,this,this._el_62);
    var compView_62:any = import15.viewFactory_Item0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Item_62_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_62),this.renderer);
    this._ItemContent_62_5 = new import15.Wrapper_ItemContent();
    this._query_Label_62_0 = new import16.QueryList<any>();
    this._query_Button_62_1 = new import16.QueryList<any>();
    this._query_Icon_62_2 = new import16.QueryList<any>();
    this._appEl_62.initComponent(this._Item_62_4.context,([] as any[]),compView_62);
    this._text_63 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_64 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_64,'color','dark');
    this.renderer.setElementAttribute(this._el_64,'stacked','');
    this._Label_64_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_64),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Notes',(null as any));
    this._text_66 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_67 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this._appEl_67 = new import3.AppElement(67,62,this,this._el_67);
    var compView_67:any = import19.viewFactory_TextArea0(this.viewUtils,this.injector(67),this._appEl_67);
    this._TextArea_67_4 = new import19.Wrapper_TextArea(this.parentInjector.get(import21.Config),this.parentInjector.get(import31.Form),this._Item_62_4.context,this.parentInjector.get(import24.App),this.parentInjector.get(import32.Platform),new import22.ElementRef(this._el_67),this.renderer,this._Content_9_4.context,this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import33.NgControl,(null as any)));
    this._appEl_67.initComponent(this._TextArea_67_4.context,([] as any[]),compView_67);
    compView_67.create(this._TextArea_67_4.context,([] as any[]),(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_62_0.reset([this._Label_64_3.context]);
    this._Item_62_4.context.contentLabel = this._query_Label_62_0.first;
    compView_62.create(this._Item_62_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_64]),
      ([] as any[]).concat([
        this._text_63,
        this._text_66,
        this._text_68
      ]
      ),
      ([] as any[]).concat([this._el_67]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_69 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','item item-block');
    this.renderer.setElementAttribute(this._el_70,'detail-none','');
    this.renderer.setElementAttribute(this._el_70,'ion-item','');
    this._appEl_70 = new import3.AppElement(70,11,this,this._el_70);
    var compView_70:any = import15.viewFactory_Item0(this.viewUtils,this.injector(70),this._appEl_70);
    this._Item_70_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_70),this.renderer);
    this._ItemContent_70_5 = new import15.Wrapper_ItemContent();
    this._query_Label_70_0 = new import16.QueryList<any>();
    this._query_Button_70_1 = new import16.QueryList<any>();
    this._query_Icon_70_2 = new import16.QueryList<any>();
    this._appEl_70.initComponent(this._Item_70_4.context,([] as any[]),compView_70);
    this._text_71 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_72 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_72,'color','primary');
    this._Label_72_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_72),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Send Message',(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_70_0.reset([this._Label_72_3.context]);
    this._Item_70_4.context.contentLabel = this._query_Label_70_0.first;
    compView_70.create(this._Item_70_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_72]),
      ([] as any[]).concat([
        this._text_71,
        this._text_74
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_75 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','item item-block');
    this.renderer.setElementAttribute(this._el_76,'detail-none','');
    this.renderer.setElementAttribute(this._el_76,'ion-item','');
    this._appEl_76 = new import3.AppElement(76,11,this,this._el_76);
    var compView_76:any = import15.viewFactory_Item0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Item_76_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_76),this.renderer);
    this._ItemContent_76_5 = new import15.Wrapper_ItemContent();
    this._query_Label_76_0 = new import16.QueryList<any>();
    this._query_Button_76_1 = new import16.QueryList<any>();
    this._query_Icon_76_2 = new import16.QueryList<any>();
    this._appEl_76.initComponent(this._Item_76_4.context,([] as any[]),compView_76);
    this._text_77 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_78 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_78,'color','primary');
    this._Label_78_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_78),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'Share Contact',(null as any));
    this._text_80 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_76_0.reset([this._Label_78_3.context]);
    this._Item_76_4.context.contentLabel = this._query_Label_76_0.first;
    compView_76.create(this._Item_76_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_78]),
      ([] as any[]).concat([
        this._text_77,
        this._text_80
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_81 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','item item-block');
    this.renderer.setElementAttribute(this._el_82,'detail-none','');
    this.renderer.setElementAttribute(this._el_82,'ion-item','');
    this._appEl_82 = new import3.AppElement(82,11,this,this._el_82);
    var compView_82:any = import15.viewFactory_Item0(this.viewUtils,this.injector(82),this._appEl_82);
    this._Item_82_4 = new import15.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_82),this.renderer);
    this._ItemContent_82_5 = new import15.Wrapper_ItemContent();
    this._query_Label_82_0 = new import16.QueryList<any>();
    this._query_Button_82_1 = new import16.QueryList<any>();
    this._query_Icon_82_2 = new import16.QueryList<any>();
    this._appEl_82.initComponent(this._Item_82_4.context,([] as any[]),compView_82);
    this._text_83 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_84 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_84,'color','primary');
    this._Label_84_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_84),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'Add to Favorites',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_82_0.reset([this._Label_84_3.context]);
    this._Item_82_4.context.contentLabel = this._query_Label_82_0.first;
    compView_82.create(this._Item_82_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_84]),
      ([] as any[]).concat([
        this._text_83,
        this._text_86
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_87 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_88 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_88
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_89 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_90 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import35.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import26.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import36.Avatar) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Avatar_15_3.context; }
    if (((token === import37.Label) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Label_20_3.context; }
    if (((token === import38.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_13_4.context; }
    if (((token === import38.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_13_5.context; }
    if (((token === import37.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3.context; }
    if (((token === import39.TextInput) && (30 === requestNodeIndex))) { return this._TextInput_30_4.context; }
    if (((token === import40.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3.context; }
    if (((token === import40.Icon) && (34 === requestNodeIndex))) { return this._Icon_34_3.context; }
    if (((token === import38.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item_25_4.context; }
    if (((token === import38.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ItemContent_25_5.context; }
    if (((token === import37.Label) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Label_39_3.context; }
    if (((token === import39.TextInput) && (42 === requestNodeIndex))) { return this._TextInput_42_4.context; }
    if (((token === import38.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Item_37_4.context; }
    if (((token === import38.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ItemContent_37_5.context; }
    if (((token === import37.Label) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Label_47_3.context; }
    if (((token === import39.TextInput) && (50 === requestNodeIndex))) { return this._TextInput_50_4.context; }
    if (((token === import38.Item) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Item_45_4.context; }
    if (((token === import38.ItemContent) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ItemContent_45_5.context; }
    if (((token === import37.Label) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Label_55_3.context; }
    if (((token === import39.TextArea) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._TextArea_58_4.context; }
    if (((token === import38.Item) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Item_53_4.context; }
    if (((token === import38.ItemContent) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ItemContent_53_5.context; }
    if (((token === import37.Label) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Label_64_3.context; }
    if (((token === import39.TextArea) && (67 === requestNodeIndex))) { return this._TextArea_67_4.context; }
    if (((token === import38.Item) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Item_62_4.context; }
    if (((token === import38.ItemContent) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._ItemContent_62_5.context; }
    if (((token === import37.Label) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Label_72_3.context; }
    if (((token === import38.Item) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Item_70_4.context; }
    if (((token === import38.ItemContent) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._ItemContent_70_5.context; }
    if (((token === import37.Label) && ((78 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Label_78_3.context; }
    if (((token === import38.Item) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Item_76_4.context; }
    if (((token === import38.ItemContent) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._ItemContent_76_5.context; }
    if (((token === import37.Label) && ((84 <= requestNodeIndex) && (requestNodeIndex <= 85)))) { return this._Label_84_3.context; }
    if (((token === import38.Item) && ((82 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._Item_82_4.context; }
    if (((token === import38.ItemContent) && ((82 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._ItemContent_82_5.context; }
    if (((token === import41.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 87)))) { return this._List_11_3.context; }
    if (((token === import42.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._List_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Item_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    this._ItemContent_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Avatar_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Label_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ItemContent_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_3:any = 'primary';
    this._Label_27_3.check_color(currVal_3,throwOnChange,false);
    this._Label_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_4:any = '+1 (555) 123-1234';
    this._TextInput_30_4.check_value(currVal_4,throwOnChange,false);
    const currVal_5:any = 'tel';
    this._TextInput_30_4.check_type(currVal_5,throwOnChange,false);
    this._TextInput_30_4.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_6:any = 'primary';
    this._Icon_32_3.check_color(currVal_6,throwOnChange,false);
    const currVal_7:any = 'ios-chatbubbles-outline';
    this._Icon_32_3.check_ios(currVal_7,throwOnChange,false);
    const currVal_8:any = 'md-chatbubbles';
    this._Icon_32_3.check_md(currVal_8,throwOnChange,false);
    this._Icon_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_10:any = 'primary';
    this._Icon_34_3.check_color(currVal_10,throwOnChange,false);
    const currVal_11:any = 'ios-call-outline';
    this._Icon_34_3.check_ios(currVal_11,throwOnChange,false);
    const currVal_12:any = 'md-call';
    this._Icon_34_3.check_md(currVal_12,throwOnChange,false);
    this._Icon_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    if (this._Item_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    this._ItemContent_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_14:any = 'primary';
    this._Label_39_3.check_color(currVal_14,throwOnChange,false);
    this._Label_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_15:any = 'hi@ionic.io';
    this._TextInput_42_4.check_value(currVal_15,throwOnChange,false);
    const currVal_16:any = 'email';
    this._TextInput_42_4.check_type(currVal_16,throwOnChange,false);
    this._TextInput_42_4.detectChangesInternal(this,this._el_42,throwOnChange);
    if (this._Item_45_4.detectChangesInternal(this,this._el_45,throwOnChange)) { this._appEl_45.componentView.markAsCheckOnce(); }
    this._ItemContent_45_5.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_17:any = 'primary';
    this._Label_47_3.check_color(currVal_17,throwOnChange,false);
    this._Label_47_3.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_18:any = 'November 21, 2013';
    this._TextInput_50_4.check_value(currVal_18,throwOnChange,false);
    const currVal_19:any = 'text';
    this._TextInput_50_4.check_type(currVal_19,throwOnChange,false);
    this._TextInput_50_4.detectChangesInternal(this,this._el_50,throwOnChange);
    if (this._Item_53_4.detectChangesInternal(this,this._el_53,throwOnChange)) { this._appEl_53.componentView.markAsCheckOnce(); }
    this._ItemContent_53_5.detectChangesInternal(this,this._el_53,throwOnChange);
    const currVal_20:any = 'primary';
    this._Label_55_3.check_color(currVal_20,throwOnChange,false);
    this._Label_55_3.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_21:any = '121 S Pinckney St\nMadison WI 53703\nUnited States';
    this._TextArea_58_4.check_value(currVal_21,throwOnChange,false);
    this._TextArea_58_4.detectChangesInternal(this,this._el_58,throwOnChange);
    if (this._Item_62_4.detectChangesInternal(this,this._el_62,throwOnChange)) { this._appEl_62.componentView.markAsCheckOnce(); }
    this._ItemContent_62_5.detectChangesInternal(this,this._el_62,throwOnChange);
    const currVal_22:any = 'dark';
    this._Label_64_3.check_color(currVal_22,throwOnChange,false);
    this._Label_64_3.detectChangesInternal(this,this._el_64,throwOnChange);
    this._TextArea_67_4.detectChangesInternal(this,this._el_67,throwOnChange);
    if (this._Item_70_4.detectChangesInternal(this,this._el_70,throwOnChange)) { this._appEl_70.componentView.markAsCheckOnce(); }
    this._ItemContent_70_5.detectChangesInternal(this,this._el_70,throwOnChange);
    const currVal_23:any = 'primary';
    this._Label_72_3.check_color(currVal_23,throwOnChange,false);
    this._Label_72_3.detectChangesInternal(this,this._el_72,throwOnChange);
    if (this._Item_76_4.detectChangesInternal(this,this._el_76,throwOnChange)) { this._appEl_76.componentView.markAsCheckOnce(); }
    this._ItemContent_76_5.detectChangesInternal(this,this._el_76,throwOnChange);
    const currVal_24:any = 'primary';
    this._Label_78_3.check_color(currVal_24,throwOnChange,false);
    this._Label_78_3.detectChangesInternal(this,this._el_78,throwOnChange);
    if (this._Item_82_4.detectChangesInternal(this,this._el_82,throwOnChange)) { this._appEl_82.componentView.markAsCheckOnce(); }
    this._ItemContent_82_5.detectChangesInternal(this,this._el_82,throwOnChange);
    const currVal_25:any = 'primary';
    this._Label_84_3.check_color(currVal_25,throwOnChange,false);
    this._Label_84_3.detectChangesInternal(this,this._el_84,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset(([] as any[]));
        this._Item_13_4.context._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset(([] as any[]));
        this._Item_13_4.context._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset([
          this._Icon_32_3.context,
          this._Icon_34_3.context
        ]
        );
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset(([] as any[]));
        this._Item_37_4.context._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset(([] as any[]));
        this._Item_37_4.context._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if (this._query_Button_45_1.dirty) {
        this._query_Button_45_1.reset(([] as any[]));
        this._Item_45_4.context._buttons = this._query_Button_45_1;
        this._query_Button_45_1.notifyOnChanges();
      }
      if (this._query_Icon_45_2.dirty) {
        this._query_Icon_45_2.reset(([] as any[]));
        this._Item_45_4.context._icons = this._query_Icon_45_2;
        this._query_Icon_45_2.notifyOnChanges();
      }
      if (this._query_Button_53_1.dirty) {
        this._query_Button_53_1.reset(([] as any[]));
        this._Item_53_4.context._buttons = this._query_Button_53_1;
        this._query_Button_53_1.notifyOnChanges();
      }
      if (this._query_Icon_53_2.dirty) {
        this._query_Icon_53_2.reset(([] as any[]));
        this._Item_53_4.context._icons = this._query_Icon_53_2;
        this._query_Icon_53_2.notifyOnChanges();
      }
      if (this._query_Button_62_1.dirty) {
        this._query_Button_62_1.reset(([] as any[]));
        this._Item_62_4.context._buttons = this._query_Button_62_1;
        this._query_Button_62_1.notifyOnChanges();
      }
      if (this._query_Icon_62_2.dirty) {
        this._query_Icon_62_2.reset(([] as any[]));
        this._Item_62_4.context._icons = this._query_Icon_62_2;
        this._query_Icon_62_2.notifyOnChanges();
      }
      if (this._query_Button_70_1.dirty) {
        this._query_Button_70_1.reset(([] as any[]));
        this._Item_70_4.context._buttons = this._query_Button_70_1;
        this._query_Button_70_1.notifyOnChanges();
      }
      if (this._query_Icon_70_2.dirty) {
        this._query_Icon_70_2.reset(([] as any[]));
        this._Item_70_4.context._icons = this._query_Icon_70_2;
        this._query_Icon_70_2.notifyOnChanges();
      }
      if (this._query_Button_76_1.dirty) {
        this._query_Button_76_1.reset(([] as any[]));
        this._Item_76_4.context._buttons = this._query_Button_76_1;
        this._query_Button_76_1.notifyOnChanges();
      }
      if (this._query_Icon_76_2.dirty) {
        this._query_Icon_76_2.reset(([] as any[]));
        this._Item_76_4.context._icons = this._query_Icon_76_2;
        this._query_Icon_76_2.notifyOnChanges();
      }
      if (this._query_Button_82_1.dirty) {
        this._query_Button_82_1.reset(([] as any[]));
        this._Item_82_4.context._buttons = this._query_Button_82_1;
        this._query_Button_82_1.notifyOnChanges();
      }
      if (this._query_Icon_82_2.dirty) {
        this._query_Icon_82_2.reset(([] as any[]));
        this._Item_82_4.context._icons = this._query_Icon_82_2;
        this._query_Icon_82_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_13_4.context.ngAfterContentInit(); }
      this._TextInput_30_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      this._TextInput_42_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_37_4.context.ngAfterContentInit(); }
      this._TextInput_50_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_45_4.context.ngAfterContentInit(); }
      this._TextArea_58_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_53_4.context.ngAfterContentInit(); }
      this._TextArea_67_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_62_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_70_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_76_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_82_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_9:any = this._Icon_32_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Icon_34_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_34,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._TextInput_30_4.context.ngOnDestroy();
    this._Icon_32_3.context.ngOnDestroy();
    this._Icon_34_3.context.ngOnDestroy();
    this._TextInput_42_4.context.ngOnDestroy();
    this._TextInput_50_4.context.ngOnDestroy();
    this._TextArea_58_4.context.ngOnDestroy();
    this._TextArea_67_4.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_ApiDemoPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ApiDemoPage> {
  if ((renderType_ApiDemoPage === (null as any))) { (renderType_ApiDemoPage = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_ApiDemoPage,{})); }
  return new _View_ApiDemoPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_ApiDemoApp_Host:import2.RenderComponentType = (null as any);
class _View_ApiDemoApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ApiDemoApp_0_4:Wrapper_ApiDemoApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoApp_Host0,renderType_ApiDemoApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ApiDemoApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ApiDemoApp_0_4 = new Wrapper_ApiDemoApp();
    this._appEl_0.initComponent(this._ApiDemoApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ApiDemoApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApiDemoApp) && (0 === requestNodeIndex))) { return this._ApiDemoApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApiDemoApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ApiDemoApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ApiDemoApp_Host === (null as any))) { (renderType_ApiDemoApp_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ApiDemoApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const ApiDemoAppNgFactory:import9.ComponentFactory<import0.ApiDemoApp> = new import9.ComponentFactory<import0.ApiDemoApp>('ng-component',viewFactory_ApiDemoApp_Host0,import0.ApiDemoApp);
const styles_ApiDemoApp:any[] = ([] as any[]);
var renderType_ApiDemoApp:import2.RenderComponentType = (null as any);
class _View_ApiDemoApp0 extends import1.AppView<import0.ApiDemoApp> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Nav_0_4:import43.Wrapper_Nav;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ApiDemoApp0,renderType_ApiDemoApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import43.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import43.Wrapper_Nav(this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import44.NavControllerBase,(null as any)),this.parentInjector.get(import24.App),this.parentInjector.get(import21.Config),this.parentInjector.get(import27.Keyboard),new import22.ElementRef(this._el_0),this.parentInjector.get(import28.NgZone),this.renderer,this.parentInjector.get(import45.ComponentFactoryResolver),this.parentInjector.get(import30.GestureController),this.parentInjector.get(import46.TransitionController),this.parentInjector.get(import47.DeepLinker,(null as any)));
    this._appEl_0.initComponent(this._Nav_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Nav_0_4.context,([] as any[]),(null as any));
    this.init(([] as any[]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.root;
    this._Nav_0_4.check_root(currVal_0,throwOnChange,false);
    this._Nav_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.context.ngAfterViewInit(); } }
  }
}
export function viewFactory_ApiDemoApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ApiDemoApp> {
  if ((renderType_ApiDemoApp === (null as any))) { (renderType_ApiDemoApp = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_ApiDemoApp,{})); }
  return new _View_ApiDemoApp0(viewUtils,parentInjector,declarationEl);
}